/**

 * 
 */

/** 
 * <!-- begin-UML-doc -->
 * <!-- end-UML-doc -->
 * @author bcouturi
 * @generated "UML to Java (com.ibm.xtools.transform.uml2.java5.internal.UML2JavaTransform)"
 */
public class createLoginAccountControl {
	/** 
	* <!-- begin-UML-doc -->
	* <!-- end-UML-doc -->
	* @generated "UML to Java (com.ibm.xtools.transform.uml2.java5.internal.UML2JavaTransform)"
	*/
	private DataManager dataManager;

	
	public createLoginAccountControl(DataManager dm) {
		dataManager = dm;
	}
	
	
	/** 
	* <!-- begin-UML-doc -->
	* <!-- end-UML-doc -->
	* @generated "UML to Java (com.ibm.xtools.transform.uml2.java5.internal.UML2JavaTransform)"
	*/
	public void createStudent() {
		// begin-user-code
		// TODO Auto-generated method stub

		// end-user-code
	}

	/** 
	* <!-- begin-UML-doc -->
	* <!-- end-UML-doc -->
	* @generated "UML to Java (com.ibm.xtools.transform.uml2.java5.internal.UML2JavaTransform)"
	*/
	public void createTA() {
		// begin-user-code
		// TODO Auto-generated method stub

		// end-user-code
	}

	/** 
	* <!-- begin-UML-doc -->
	* <!-- end-UML-doc -->
	* @generated "UML to Java (com.ibm.xtools.transform.uml2.java5.internal.UML2JavaTransform)"
	*/
	public void createProf() {
		// begin-user-code
		// TODO Auto-generated method stub

		// end-user-code
	}

	/** 
	* <!-- begin-UML-doc -->
	* <!-- end-UML-doc -->
	* @generated "UML to Java (com.ibm.xtools.transform.uml2.java5.internal.UML2JavaTransform)"
	*/
	public void createAdmin() {
		// begin-user-code
		// TODO Auto-generated method stub

		// end-user-code
	}
}

 * Control class for the 'createLoginAccount' admin use case.
 * @author Ben Donkin
 *
 */
public class createLoginAccountControl {
	
	private DataManager dataManager;

	
	public createLoginAccountControl() {
		dataManager = MainMenu.getDataManager();
	}
	
	/**
	 * 
	 * @param acc
	 * @param type
	 * @return the accountId that was automatically generated by mysql
	 */
	public int createAccount(Account acc) {
		return dataManager.handleCreateAccount(acc, acc.getAccountType());
	}
	
	public void createStudent(StudentAccount studAcc) {
		dataManager.handleCreateStudent(studAcc);
	}

	
	public void createTA(TA_Account TA_Acc) {
		dataManager.handleCreateTA(TA_Acc);
	}

	
	public void createProf(ProfessorAccount profAc) {
		dataManager.handleCreateProf(profAc);
	}

	
	public void createAdmin(AdminAccount adminAc) {
		dataManager.handleCreateAdmin(adminAc);
	}
}
